@accessToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxNDYzOTk0MzQiLCJ1c2VybmFtZSI6IlBsYXN0aWNQbGFjdGljZSIsImlhdCI6MTc1NDgwMDIzMSwiZXhwIjoxNzU0ODAzODMxfQ.-Woe2A1ncQ_NcE9fsH39IRHJv_qB0EfB5nqHeIg4Ttv27K7Gj68RGwiqyo3izOdL
###
POST http://localhost:8080/api/devlogs
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "logDate": "2024-05-20",
  "keepContent": "要件定義がスムーズに進んだ。",
  "problemContent": "データベースの設計に時間がかかった。",
  "tryContent": "次回はER図を先に作成する。",
  "goalContent": "APIのCRUD機能を全て完成させる。",
  "user": { "id": 1 },
  "project": { "id": 1 }
}

### すべての開発ログを取得 (GET)
GET http://localhost:8080/api/devlogs
Authorization: Bearer {{accessToken}}
Accept: application/json
